"""Scene Program serialization helpers."""

from __future__ import annotations

import json
from pathlib import Path

from smcb.dsl.models import SceneProgram


def load_scene(path: Path) -> SceneProgram:
    """Read and validate one Scene Program JSON file."""
    return SceneProgram.model_validate_json(path.read_text(encoding="utf-8"))


def write_scene(scene: SceneProgram, path: Path) -> None:
    """Write canonical, human-readable Scene Program JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(scene.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def write_json_schema(path: Path) -> None:
    """Materialize the versioned JSON Schema generated by Pydantic."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(SceneProgram.model_json_schema(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
